// eslint-disable-next-line import/prefer-default-export
export const data = [
  {
    date: "2023/10/25",
    time: 7,
    totalSleepHours: 7,
    remSleepPercentage: 20,
    deepSleepPercentage: 25,
    sleepEfficiency: "Easy",
    awakenings: 2,
  },
  {
    date: "2023/10/26",
    time: 6.5,
    totalSleepHours: 6.5,
    remSleepPercentage: 15,
    deepSleepPercentage: 20,
    sleepEfficiency: "Easy",
    awakenings: 3,
  },
  {
    date: "2023/10/27",
    time: 6.5,
    totalSleepHours: 6.5,
    remSleepPercentage: 25,
    deepSleepPercentage: 22,
    sleepEfficiency: "Medium",
    awakenings: 1,
  },
  {
    date: "2023/10/28",
    time: 5,
    totalSleepHours: 5,
    remSleepPercentage: 18,
    deepSleepPercentage: 20,
    sleepEfficiency: "Easy",
    awakenings: 4,
  },
  {
    date: "2023/10/29",
    time: 10.5,
    totalSleepHours: 10.5,
    remSleepPercentage: 22,
    deepSleepPercentage: 28,
    sleepEfficiency: "Medium",
    awakenings: 0,
  },
  {
    date: "2023/10/30",
    time: 8.5,
    totalSleepHours: 8.5,
    remSleepPercentage: 20,
    deepSleepPercentage: 24,
    sleepEfficiency: "Easy",
    awakenings: 2,
  },
  {
    date: "2023/10/31",
    time: 8.5,
    totalSleepHours: 8.5,
    remSleepPercentage: 16,
    deepSleepPercentage: 25,
    sleepEfficiency: "Easy",
    awakenings: 2,
  },
  {
    date: "2023/11/01",
    time: 7.5,
    totalSleepHours: 7.5,
    remSleepPercentage: 19,
    deepSleepPercentage: 21,
    sleepEfficiency: "Medium",
    awakenings: 3,
  },
  {
    date: "2023/11/02",
    time: 9.5,
    totalSleepHours: 9.5,
    remSleepPercentage: 17,
    deepSleepPercentage: 26,
    sleepEfficiency: "Medium",
    awakenings: 1,
  },
  {
    date: "2023/11/03",
    time: 9.5,
    totalSleepHours: 9.5,
    remSleepPercentage: 23,
    deepSleepPercentage: 27,
    sleepEfficiency: "Hard",
    awakenings: 1,
  },
  {
    date: "2023/11/04",
    time: 7.5,
    totalSleepHours: 7.5,
    remSleepPercentage: 20,
    deepSleepPercentage: 23,
    sleepEfficiency: "Hard",
    awakenings: 2,
  },
  {
    date: "2023/11/05",
    time: 7.5,
    totalSleepHours: 7.5,
    remSleepPercentage: 21,
    deepSleepPercentage: 22,
    sleepEfficiency: "Hard",
    awakenings: 2,
  },
  {
    date: "2023/11/06",
    time: 7.5,
    totalSleepHours: 7.5,
    remSleepPercentage: 18,
    deepSleepPercentage: 20,
    sleepEfficiency: "Hard",
    awakenings: 3,
  },
  {
    date: "2023/11/07",
    time: 7.5,
    totalSleepHours: 7.5,
    remSleepPercentage: 19,
    deepSleepPercentage: 24,
    sleepEfficiency: "Hard",
    awakenings: 3,
  },
  {
    date: "2023/11/08",
    time: 8.5,
    totalSleepHours: 8.5,
    remSleepPercentage: 22,
    deepSleepPercentage: 25,
    sleepEfficiency: "Medium",
    awakenings: 2,
  },
  {
    date: "2023/11/09",
    time: 8.5,
    totalSleepHours: 8.5,
    remSleepPercentage: 20,
    deepSleepPercentage: 23,
    sleepEfficiency: "Medium",
    awakenings: 2,
  },
];
